# Generated by Django 4.2.7 on 2023-11-26 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('user_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, help_text='Your Phone number', max_length=15, null=True)),
                ('initials', models.CharField(blank=True, default='', help_text='Your Initials', max_length=10, null=True)),
                ('thumbnail', models.URLField(blank=True, help_text='The Thumbnail', max_length=256, null=True)),
                ('password_status', models.CharField(choices=[('T', 'Temporary'), ('S', 'Set')], default='T', max_length=1)),
                ('password_version', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForgotPasswordRequests',
            fields=[
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('forgot_password_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(default=uuid.uuid4)),
                ('is_satisfied', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ForgotPasswordRequests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
